### ISSUE TITLE
launch tracker

### ISSUE THREAD

**Issue by opxdelwin** [tech-mySanji/branch_manager_app_archive#11]
All issues will be switched to purple circle when closed, and will contain any PR (Merge Requests) as a sub text.
All issue based communications may be done within the issue thread itself.

### Customer App

- [ ] https://github.com/tech-mySanji/customer_app_archive/issues/1
- [ ] https://github.com/tech-mySanji/customer_app_archive/issues/2
- [ ] https://github.com/tech-mySanji/customer_app_archive/issues/3

### Vendor App

- [ ] https://github.com/tech-mySanji/vendor_app_archive/issues/1
- [ ] https://github.com/tech-mySanji/vendor_app_archive/issues/2
- [ ] https://github.com/tech-mySanji/vendor_app_archive/issues/3
- [ ] https://github.com/tech-mySanji/vendor_app_archive/issues/4
- [ ] https://github.com/tech-mySanji/vendor_app_archive/issues/5
- [ ] https://github.com/tech-mySanji/vendor_app_archive/issues/6
- [ ] https://github.com/tech-mySanji/vendor_app_archive/issues/7
- [ ] https://github.com/tech-mySanji/vendor_app_archive/issues/8

### Branch Manager App

- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/1
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/2
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/3
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/4
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/5
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/6
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/7
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/8
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/9
- [ ] https://github.com/tech-mySanji/branch_manager_app_archive/issues/10

### Delivery App

- [ ] https://github.com/tech-mySanji/delivery_app_archive/issues/1
- [ ] https://github.com/tech-mySanji/delivery_app_archive/issues/2
- [ ] https://github.com/tech-mySanji/delivery_app_archive/issues/3
- [ ] https://github.com/tech-mySanji/delivery_app_archive/issues/4
- [ ] https://github.com/tech-mySanji/delivery_app_archive/issues/5
- [ ] https://github.com/tech-mySanji/delivery_app_archive/issues/6
